name: Generate Code with AI

on:
  schedule:
    - cron: '0 0 * * *'  # Se ejecuta diariamente a medianoche (UTC)
  workflow_dispatch:  # Esto permite que ejecutes el workflow manualmente


jobs:
  generate-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install openai

      - name: Run AI code generation script
        env:
          DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
        run: |
          python scripts/generate_code.py

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "figueroariveraenrique@gmail.com"
          git config --global user.name "Enrique-Figue"
          git add .
          git commit -m "Add code generated by AI" || echo "No changes to commit"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/Enrique-Figue/code-generator.git
          git push origin HEAD

